# Generated by Django 3.2.8 on 2021-12-08 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonctionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('login', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('sexe', models.CharField(max_length=60)),
                ('fonction', models.CharField(max_length=60)),
                ('situation_matrimoniale', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Enfant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('sexe', models.CharField(max_length=60)),
                ('lieu_naissance', models.CharField(max_length=60)),
                ('date_naissance', models.DateField(default='')),
                ('annee_naissance', models.CharField(max_length=60)),
                ('fonctionnaire', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nouveaune.fonctionnaire')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nouveaune.parent')),
            ],
        ),
    ]
